FROM cachyos/cachyos:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
    base-devel \
    cmake \
    ninja \
    git \
    gcc \
    clang \
    python \
    curl \
    wget \
    zip \
    unzip \
    tar \
    mono \
    buildcache-git
