name: Build & Test

on:
  push: { branches: ["master"] }
  pull_request: { branches: ["master"] }
  workflow_dispatch:

permissions: { contents: read, packages: write }

jobs:
  linux:
    name: Linux (${{ matrix.compiler }})
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    uses: ./.github/workflows/linux-pipeline.yml
    with:
      compiler: ${{ matrix.compiler }}
    secrets: inherit

  windows:
    name: Windows (${{ matrix.compiler }})
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc, clang]

    uses: ./.github/workflows/windows-pipeline.yml
    with:
      compiler: ${{ matrix.compiler }}
    secrets: inherit
