name: Windows Pipeline

on:
  workflow_call:
    inputs:
      compiler:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Windows (${{ inputs.compiler }})
    runs-on: windows-latest
    defaults:
      run:
        shell: bash # Forces Git Bash for consistency with Linux scripts

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-windows
        with:
          compiler: ${{ inputs.compiler }}

      - name: Build
        uses: ./.github/actions/build-lbs
        with:
          cache_prefix: windows
          preset: ci_windows_${{ inputs.compiler }}

      - name: Test
        uses: ./.github/actions/test-lbs
        with:
          preset: ci_windows_${{ inputs.compiler }}
